config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: :create
  end

  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(
      content: params[:comment][:content],
      post: Post.find(params[:post_id]),
      user: current_user
    )
    @comment.save
    respond_to :js
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
   respond_to do |format|
     if !params[:buscador].nil?
       if params[:buscador].length < 3
         @posts = Post.order(:id)
       else
         @posts = Post.where('title LIKE ?', "%#{params[:buscador]}%")
       end
       format.js
     else
       @posts = Post.order(:id)
       format.html
     end
   end
   @post = Post.new
  end

  def create
    @post = Post.new(
      title: params[:post][:title],
      user_id: current_user.id
    )
    @post.save
    respond_to :js
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to :js
  end

  def edit
    @post = Post.find(params[:id])
    respond_to :js
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.save
    respond_to :js
  end

  def show
    @post = Post.find(params[:id])
    respond_to :js
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.js.erb
$('#post_comments_list').append("<li><%= @comment.content %></li>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
			  src="https://code.jquery.com/jquery-3.3.1.min.js"
			  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
			  crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="container">  
  <%= yield %>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_comment_form.html.erb
<%= form_with(model: [post, comment]) do |f| %>
<%= f.label :content %>
<%= f.text_field :content %>
<%= f.submit %>
<% end %>

<ul id= "post_comments_list">
<% post.comments.each do |c| %>
<li><%= c.content %></li>
<% end %>
</ul>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/posts/_post.html.erb
<li id="<%=post.id%>"><%= post.title %>
<%= link_to 'Eliminar', post, method: :delete, data: {confirm: 'Estás seguro?', remote: true} %>
<%= link_to 'Editar', edit_post_path(post.id), data: {remote: true}%>
<%= link_to 'Show', post_path(post.id), data: {remote: true}%></li>

app/views/posts/create.js.erb
$('#post_list').append('<%= j render @post %>')

app/views/posts/destroy.js.erb
$("#<%=@post.id %>").toggle(1000);

app/views/posts/edit.js.erb
$('.modal-body').html("<%= j render 'form', post: @post %>")
$('#modal-edit').modal('show')

app/views/posts/index.html.erb
<h1>Posts#index</h1>

<%= render 'form', post: @post %>

<ul id="post_list">
  <%= render @posts %>
</ul>

<br>
<label for="">Buscar:</label>
<input type="text" id="buscador">
<script>
 $('#buscador').keyup(function () {

  var searchQuery = $('#buscador').val();
  $.ajax({
    type: "GET",
    url: "<%= posts_path %>",
    data: {buscador: searchQuery}
  });
});
</script>

<%# Este es el modal: %>
<div id="modal-edit" class="modal fade" tabindex="-1" role="dialog">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <h5 class="modal-title">Modal title</h5>
       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         <span aria-hidden="true">&times;</span>
       </button>
     </div>
     <div class="modal-body">

     </div>
   </div>
 </div>
</div>

app/views/posts/index.js.erb
$('#post_list').html("<%= j render @posts %>");

app/views/posts/show.js.erb
$('.modal-body').html("<h4><%= @post.title %></h4> <%= j render 'comment_form', post: @post, comment: Comment.new %>")
$('#modal-edit').modal('show')

app/views/posts/update.js.erb
$('#<%= @post.id %>').replaceWith("<%= j render @post %>")
$('modal-edit').modal('hide')

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">HOME</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
     <% if user_signed_in? %>
      <li><a href="#" class="nav-link"><%=current_user.email %></a></li>
      <li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
    <% else %>
      <li><%= link_to 'Inicia sesión', new_user_session_path, class: 'nav-link' %></li>
      <li><%= link_to 'Regístrate', new_user_registration_path, class: 'nav-link' %></li>
    <% end %>
    </ul>
  </div>
</nav>